Fix autobackend.py when using OpenVINO
This error occurred with 8.3.227, but it's also present in 8.4.9:

ultralytics/nn/autobackend.py", line 316, in __init__
    inference_mode = "CUMULATIVE_THROUGHPUT" if batch > 1 and dynamic else "LATENCY"
                                                ^^^^^
UnboundLocalError: cannot access local variable 'batch' where it is not associated with a value

The problem is that "dynamic" is declared with False as its
default value, but "batch" isn't declared.

The assignment that creates "batch" is just above the assignment
to inference_mode, but it's conditionally executed if metadata.yaml
exists.

Flip the order of the check, so "batch" is correctly ignored
when "dynamic" is False.

Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>