Compute the available space for the current path
When downloading a file, we need to check for the available space for the current working drive.

The thing is on windows the current drive is not '/' but 'C:\\' which with the previous version generates the following error:

```bash
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect
```