Update plotting.py
Pillow 10 will cause AttributeError: 'FreeTypeFont' object has no attribute 'getsize', the 'getsize' attribute exists in Pillow 9.5.