Update augment.py
Avoid potential error by
sampled_labels = pos_labels + neg_labels
TypeError: unsupported operand type(s) for +: 'set' and 'list'

e.g., pos_labels is a set e.g., {1,2,3}
but neg_labels is a list [], they will cause an error.